// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeploymentStatus string

const (
	DeploymentStatusQUEUE    DeploymentStatus = "QUEUE"
	DeploymentStatusPROGRESS DeploymentStatus = "PROGRESS"
	DeploymentStatusREADY    DeploymentStatus = "READY"
	DeploymentStatusFAIL     DeploymentStatus = "FAIL"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type Deployment struct {
	ID        int64            `json:"id"`
	ProjectID pgtype.Int8      `json:"project_id"`
	Status    DeploymentStatus `json:"status"`
}

type Project struct {
	ID           int64              `json:"id"`
	CreatedBy    pgtype.Int4        `json:"created_by"`
	Name         string             `json:"name"`
	GithubUrl    string             `json:"github_url"`
	Subdomain    pgtype.Text        `json:"subdomain"`
	CustomDomain pgtype.Text        `json:"custom_domain"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID     uuid.UUID          `json:"id"`
	Token  string             `json:"token"`
	UserID int32              `json:"user_id"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type User struct {
	ID       int32       `json:"id"`
	GithubID int32       `json:"github_id"`
	Username string      `json:"username"`
	Name     pgtype.Text `json:"name"`
	Email    string      `json:"email"`
	Avatar   pgtype.Text `json:"avatar"`
}
