// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: service_hyperion.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HyperionClient is the client API for Hyperion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HyperionClient interface {
	DeployProject(ctx context.Context, in *DeployProjectRequest, opts ...grpc.CallOption) (*DeployProjectResponse, error)
}

type hyperionClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperionClient(cc grpc.ClientConnInterface) HyperionClient {
	return &hyperionClient{cc}
}

func (c *hyperionClient) DeployProject(ctx context.Context, in *DeployProjectRequest, opts ...grpc.CallOption) (*DeployProjectResponse, error) {
	out := new(DeployProjectResponse)
	err := c.cc.Invoke(ctx, "/pb.Hyperion/DeployProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperionServer is the server API for Hyperion service.
// All implementations must embed UnimplementedHyperionServer
// for forward compatibility
type HyperionServer interface {
	DeployProject(context.Context, *DeployProjectRequest) (*DeployProjectResponse, error)
	mustEmbedUnimplementedHyperionServer()
}

// UnimplementedHyperionServer must be embedded to have forward compatible implementations.
type UnimplementedHyperionServer struct {
}

func (UnimplementedHyperionServer) DeployProject(context.Context, *DeployProjectRequest) (*DeployProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployProject not implemented")
}
func (UnimplementedHyperionServer) mustEmbedUnimplementedHyperionServer() {}

// UnsafeHyperionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyperionServer will
// result in compilation errors.
type UnsafeHyperionServer interface {
	mustEmbedUnimplementedHyperionServer()
}

func RegisterHyperionServer(s grpc.ServiceRegistrar, srv HyperionServer) {
	s.RegisterService(&Hyperion_ServiceDesc, srv)
}

func _Hyperion_DeployProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperionServer).DeployProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Hyperion/DeployProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperionServer).DeployProject(ctx, req.(*DeployProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hyperion_ServiceDesc is the grpc.ServiceDesc for Hyperion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hyperion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Hyperion",
	HandlerType: (*HyperionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployProject",
			Handler:    _Hyperion_DeployProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_hyperion.proto",
}
